# Generated by Django 2.1.5 on 2019-09-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100, verbose_name='Тип документа')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('given_by', models.CharField(max_length=100, verbose_name='Выдан кем')),
                ('given_at', models.DateField(verbose_name='Дата выдачи')),
                ('note', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Примечание')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Фотография документа')),
            ],
            options={
                'verbose_name': ('Документ',),
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='actual_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Фактический адрес проживания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_place',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Населенный пункт'),
        ),
    ]
