# Generated by Django 2.1.5 on 2019-09-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmdocument',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ConfirmDocument',
        ),
    ]
