# Generated by Django 2.1.5 on 2019-09-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190918_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_password_changed_at',
            field=models.DateTimeField(default=None, verbose_name='Пароль изменен'),
        ),
    ]
