# Generated by Django 2.1.5 on 2019-09-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190917_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmdocument',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_document', to='accounts.Client', verbose_name='Владелец'),
        ),
    ]
