# Generated by Django 2.1.5 on 2019-12-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191202_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'default_permissions': (), 'permissions': (('operations_view', 'Просмотр журнала операций'), ('loan_item_list_view', 'Просмотр списка залоговых имуществ'), ('add_loan', 'Добавление займа')), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
