# Generated by Django 2.1.5 on 2019-09-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190923_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='Test', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Cashier', 'Cashier'), ('Auditor', 'Auditor')], default='Auditor', max_length=100, verbose_name='Тип прав'),
        ),
    ]
