# Generated by Django 2.1.5 on 2019-11-04 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Имя категории')),
                ('interest_rate', models.DecimalField(decimal_places=1, default=None, max_digits=3, verbose_name='Процентная ставка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('location', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=100, verbose_name='Номер дома')),
                ('apartment_number', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Номер квартиры')),
                ('actual_address', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Фактический адрес проживания')),
                ('birth_place', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Место рождения')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('files', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ConfirmDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100, verbose_name='Тип документа')),
                ('iin', models.CharField(default=None, max_length=100, verbose_name='ИИН')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('given_by', models.CharField(max_length=100, verbose_name='Выдан кем')),
                ('given_at', models.DateField(verbose_name='Дата выдачи')),
                ('note', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Примечание')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Фотография документа')),
                ('client', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_document', to='pawnshop.Client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': ('Документ',),
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Название критерия')),
                ('category', models.ManyToManyField(related_name='criteria_list', to='pawnshop.Category', verbose_name='Относится к категории')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
            },
        ),
        migrations.CreateModel(
            name='CriteriaValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=None, max_length=100, verbose_name='Значение')),
                ('criteria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='criteria_values', to='pawnshop.Criteria', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Значение критерия',
                'verbose_name_plural': 'Значения критерия',
            },
        ),
        migrations.CreateModel(
            name='FakeOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Описание фейк операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fake_operations', to='pawnshop.Client', verbose_name='Относится к клиентам')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_amount', models.DecimalField(decimal_places=10, default=None, max_digits=20, verbose_name='Запрашиваемая сумма')),
                ('duration', models.IntegerField(default=5, verbose_name='Период')),
                ('date_of_expire', models.DateField(max_length=100, verbose_name='Срок погашения займа')),
                ('warranty_date', models.DateField(max_length=100, verbose_name='Дата гарантийного срока')),
                ('total_amount', models.DecimalField(decimal_places=10, default=None, max_digits=20, verbose_name='Итоговая сумма кредита')),
                ('status', models.CharField(choices=[('Открыт', 'Открыт'), ('Закрыт', 'Закрыт'), ('Истек', 'Истек')], default=None, max_length=100, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='pawnshop.Client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': ('Займ',),
                'verbose_name_plural': 'Займы',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('Выдача займа', 'Выдача займа'), ('Выкуп', 'Выкуп'), ('Пролонгация', ' Пролонгация')], default=None, max_length=100, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('amount', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='amount', to='pawnshop.Loan', verbose_name='сумма по операции')),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('loan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='pawnshop.Loan', verbose_name='номер билета')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.CreateModel(
            name='PledgeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Оценочная стоимость')),
                ('description', models.CharField(default=None, max_length=200, verbose_name='Описание')),
                ('note', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Примечание')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Фотография')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pledge_items', to='pawnshop.Category', verbose_name='Относится к категории')),
                ('loan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pledge_items', to='pawnshop.Loan', verbose_name='Займ')),
            ],
            options={
                'verbose_name': 'Предмет залога',
                'verbose_name_plural': 'Предметы залога',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Имя подкатегории')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pawnshop.Category', verbose_name='Родительская категория')),
                ('subcategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pawnshop.Subcategory', verbose_name='Родительская подкатегория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default=None, max_length=100, verbose_name='Имя файла')),
                ('file_path', models.CharField(default=None, max_length=100, verbose_name='Путь к файлу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('loan', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='pawnshop.Loan', verbose_name='Залог')),
            ],
        ),
        migrations.AddField(
            model_name='pledgeitem',
            name='subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pledge_items', to='pawnshop.Subcategory', verbose_name='Относится к подкатегории'),
        ),
        migrations.AddField(
            model_name='fakeoperation',
            name='pledge_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fake_operations', to='pawnshop.PledgeItem', verbose_name='Относится к залоговому имуществу'),
        ),
        migrations.AddField(
            model_name='criteriavalue',
            name='pledge_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='criteria_values', to='pawnshop.PledgeItem', verbose_name='Залоговое имущество'),
        ),
    ]
