# Generated by Django 2.1.5 on 2019-09-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('location', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=100, verbose_name='Номер дома')),
                ('apartment_number', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Номер квартиры')),
                ('actual_address', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Фактический адрес проживания')),
                ('birth_place', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Место рождения')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('iin', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='ИИН')),
                ('files', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
