# Generated by Django 2.1.5 on 2019-09-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100, verbose_name='Тип документа')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('given_by', models.CharField(max_length=100, verbose_name='Выдан кем')),
                ('given_at', models.DateField(verbose_name='Дата выдачи')),
                ('note', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Примечание')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Фотография документа')),
                ('owner', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_document', to='pawnshop.Client', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': ('Документ',),
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
