# Generated by Django 2.1.5 on 2019-11-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='type_operation',
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('Добавление займа', 'Добавление займа'), ('Выкуп займа', 'Выкуп займа'), ('Пролонгация займа', ' Пролонгация займа')], default=None, max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=20, verbose_name='Сумма операции'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='accounts.Users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='loan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='pawnshop.Loan', verbose_name=''),
        ),
    ]
