# Generated by Django 2.1.5 on 2019-10-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='loan',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='pawnshop.Loan', verbose_name='Залог'),
        ),
    ]
