# Generated by Django 2.1.5 on 2019-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0002_ticket_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт'), ('expired', 'Истек')], default=None, max_length=100, verbose_name='Статус'),
        ),
    ]
