# Generated by Django 2.1.5 on 2019-11-04 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0002_auto_20191104_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
