# Generated by Django 2.1.5 on 2019-09-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0002_confirmdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='iin',
        ),
        migrations.AddField(
            model_name='confirmdocument',
            name='iin',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='ИИН'),
        ),
    ]
