# Generated by Django 2.1.5 on 2019-09-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0003_auto_20190918_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmdocument',
            name='owner',
        ),
        migrations.AddField(
            model_name='confirmdocument',
            name='client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_document', to='pawnshop.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='confirmdocument',
            name='iin',
            field=models.CharField(default=None, max_length=100, verbose_name='ИИН'),
        ),
    ]
