# Generated by Django 2.1.5 on 2019-10-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0003_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Открыт', 'Открыт'), ('Закрыт', 'Закрыт'), ('Истек', 'Истек')], default=None, max_length=100, verbose_name='Статус'),
        ),
    ]
