# Generated by Django 2.1.5 on 2019-11-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0003_auto_20191104_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='loan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='pawnshop.Loan', verbose_name='Займ'),
        ),
    ]
