# Generated by Django 2.1.5 on 2019-10-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0004_auto_20191024_0723'),
        ('pawnshop', '0004_auto_20191025_1851'),
    ]

    operations = [
    ]
