# Generated by Django 2.2 on 2019-11-01 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0005_merge_20191029_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='warranty_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=100, verbose_name='Дата гарантийного срока'),
            preserve_default=False,
        ),
    ]
