# Generated by Django 2.2 on 2019-11-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0006_loan_warranty_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_of_expire',
            field=models.DateField(max_length=100, verbose_name='Срок погашения займа'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='warranty_date',
            field=models.DateField(max_length=100, verbose_name='Дата гарантийного срока'),
        ),
    ]
