# Generated by Django 2.1.5 on 2019-11-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0007_auto_20191101_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user_first_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Имя')),
                ('user_last_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Фамилия')),
                ('description_operation', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Описание операции')),
                ('type_operation', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Место рождения')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
    ]
