# Generated by Django 2.1.5 on 2019-09-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0008_auto_20190920_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaPledgeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pawnshop.Subcategory', verbose_name='Родительская подкатегория'),
        ),
    ]
