# Generated by Django 2.1.5 on 2019-11-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0008_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Тип операции'),
        ),
    ]
