# Generated by Django 2.1.5 on 2019-11-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0009_auto_20191101_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='user_first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='user_last_name',
        ),
    ]
