# Generated by Django 2.1.5 on 2019-09-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0009_auto_20190921_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Оценочная стоимость')),
                ('description', models.CharField(default=None, max_length=200, verbose_name='Описание')),
                ('note', models.CharField(default=None, max_length=100, verbose_name='Примечание')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Фотография')),
                ('subcategory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pledge_items', to='pawnshop.Subcategory', verbose_name='Относится к подкатегории')),
            ],
            options={
                'verbose_name': 'Предмет залога',
                'verbose_name_plural': 'Предметы залога',
            },
        ),
        migrations.AlterModelOptions(
            name='criteriapledgeitem',
            options={'verbose_name': 'Значение критерия', 'verbose_name_plural': 'Значения критерия'},
        ),
    ]
