# Generated by Django 2.1.5 on 2019-11-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pawnshop', '0010_auto_20191101_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='description_operation',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='username',
        ),
        migrations.AddField(
            model_name='operation',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='сумма по операции'),
        ),
        migrations.AddField(
            model_name='operation',
            name='loan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pawnshop.Loan', verbose_name='Залог'),
        ),
        migrations.AddField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Users', verbose_name='Пользователь'),
        ),
    ]
