# Generated by Django 2.1.5 on 2019-09-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0010_auto_20190921_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgeitem',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Примечание'),
        ),
    ]
