# Generated by Django 2.1.5 on 2019-11-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0011_auto_20191102_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='loan',
        ),
        migrations.AddField(
            model_name='operation',
            name='ticket_number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pawnshop.Ticket', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='pawnshop.Loan', verbose_name='сумма по операции'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('Выкуп', 'Открыт'), ('Залог', 'Закрыт'), ('Пролонгация', ' Пролонгация')], default=None, max_length=100, verbose_name='Статус'),
        ),
    ]
