# Generated by Django 2.1.5 on 2019-11-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0012_auto_20191102_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('Выдача заема', 'Выдача заема'), ('Выкуп', 'Выкуп'), ('Пролонгация', ' Пролонгация')], default=None, max_length=100, verbose_name='Статус'),
        ),
    ]
