# Generated by Django 2.2 on 2019-09-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0013_auto_20190925_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='interest_rate',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3),
        ),
        migrations.AlterField(
            model_name='loan',
            name='pledge_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='pawnshop.PledgeItem', verbose_name='Предмет залога'),
        ),
    ]
