# Generated by Django 2.1.5 on 2019-11-02 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0013_auto_20191102_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='operation_amount', to='pawnshop.Loan', verbose_name='сумма по операции'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='ticket_number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_ticket', to='pawnshop.Ticket', verbose_name='номер билета'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='username',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_user', to='accounts.Users', verbose_name='Пользователь'),
        ),
    ]
