# Generated by Django 2.1.5 on 2019-09-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0014_auto_20190925_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='interest_rate',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, verbose_name='Процентная ставка'),
        ),
    ]
