# Generated by Django 2.1.5 on 2019-09-30 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0015_auto_20190926_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Описание фейк операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fake_operations', to='pawnshop.Client', verbose_name='Относится к клиентам')),
                ('pledge_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fake_operations', to='pawnshop.PledgeItem', verbose_name='Относится к залоговому имуществу')),
            ],
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': ('Займ',), 'verbose_name_plural': 'Займы'},
        ),
    ]
