# Generated by Django 2.1.5 on 2019-10-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0017_auto_20191001_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='client_amount',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=20, verbose_name='Запрашиваемая сумма'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=20, verbose_name='Итоговая сумма кредита'),
        ),
    ]
