# Generated by Django 2.2 on 2019-10-02 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0017_auto_20191001_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='client_amount',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=20, verbose_name='Запрашиваемая сумма'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=20, verbose_name='Итоговая сумма кредита'),
        ),
    ]
