# Generated by Django 2.1.5 on 2019-10-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0018_auto_20191002_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=None, max_length=100, verbose_name='Значение')),
                ('criteria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='criteria_values', to='pawnshop.Criteria', verbose_name='Критерий')),
                ('pledge_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='criteria_values', to='pawnshop.PledgeItem', verbose_name='Залоговое имущество')),
            ],
            options={
                'verbose_name': 'Значение критерия',
                'verbose_name_plural': 'Значения критерия',
            },
        ),
        migrations.DeleteModel(
            name='CriteriaPledgeItem',
        ),
    ]
