# Generated by Django 2.1.5 on 2019-10-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0019_auto_20191002_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='category',
            field=models.ManyToManyField(related_name='criteria_list', to='pawnshop.Category', verbose_name='Относится к категории'),
        ),
    ]
