# Generated by Django 2.1.5 on 2019-10-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0018_auto_20191002_1429'),
        ('pawnshop', '0020_auto_20191002_1418'),
    ]

    operations = [
    ]
