# Generated by Django 2.1.5 on 2019-10-16 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0024_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(auto_now_add=True, verbose_name='Дата открытия кредита')),
                ('client', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='pawnshop.Client', verbose_name='клиент')),
                ('loan', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='contract_loan', to='pawnshop.Loan', verbose_name='кредит')),
                ('ticket_number', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='pawnshop.Contract', verbose_name='номер залогового билета')),
            ],
            options={
                'verbose_name': 'Залоговый билет',
                'verbose_name_plural': 'залоговые билеты',
            },
        ),
    ]
